project-backend/node_modules/.package-lock.json, project-backend/package-lock.json, project-backend/package.json, project/package-lock.json, project/src/pages/Registerscreen/index.js
=> menghilangkan codingan backend dari signup

project/package-lock.json, project/src/pages/Registerscreen/index.js, project/yarn.lock
=> Gua baru nyambungin signup dengan database

project-backend/app.js, project/src/pages/Homescreen/index.js, project/src/pages/Registerscreen/index.js, project/src/pages/Signinscreen/index.js
aku sudah mengupgrade toast alert di auth, mohon diterima ya atmin.
selanjutnya aku akan menetapkan login user
=> Mengupgrade Toast Alert di Auth

project/src/pages/Registerscreen/index.js, project/src/pages/index.js
=> mencoba push ulang

project/src/pages/Authscreen/index.js, project/src/pages/Homescreen/index.js
=> menambahkan fitur alert logout account dan fitur keluar dari apk

project/.gitignore, project/src/config.js, project/src/navigation/AuthNavigator.js, project/src/navigation/BottomTabNavigator.js, project/src/navigation/DrawerNavigator.js, project/src/pages/FAQscreen/index.js, project/src/pages/Homescreen/index.js
=> menambahkan side bar tetapi belom terpanggil di screen notification

project/src/pages/Auth/Authscreen.js, project/src/pages/Auth/Forgotpassword.js, project/src/pages/Auth/Registerscreen.js, project/src/pages/Auth/Signinscreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Home/Notificationscreen.js, project/src/pages/Home/Profilescreen.js, project/src/pages/Other/Marksscreen.js, project/src/pages/Other/Splashscreen.js, project/src/pages/Settings/FAQscreen.js, project/src/pages/Settings/Settingsscreen.js, project/src/pages/Settings/TermsandConditionscreen.js
=> perbaiki folder part 2

project-backend/node_modules/.package-lock.json, project-backend/package-lock.json, project-backend/package.json, project/App.js, project/package-lock.json, project/package.json, project/src/config.js, project/src/navigation/BottomTabNavigator.js, project/src/navigation/DrawerNavigator.js, project/src/pages/Auth/Registerscreen.js, project/src/pages/Auth/Signinscreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Settings/FAQscreen.js, project/yarn.lock
=> menambahkan contoh tweet card

project/src/components/TweetCard.js, project/src/pages/Settings/FAQscreen.js
=> menambahkan button untuk send question serta menambahkan API serta functionnya

project-backend/Model/ImageModel.js, project-backend/app.js
=> commitan model

project/src/config.js, project/src/navigation/AuthNavigator.js, project/src/pages/Auth/Capthcascreen.js, project/src/pages/Auth/CreatePassword.js, project/src/pages/Auth/Registerscreen.js, project/src/pages/Auth/Signinscreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Settings/Settingsscreen.js, project/src/pages/index.js
=> front end forgot password

project-backend/.gitignore, project-backend/app.js, project-backend/vercel.json, project/package-lock.json, project/package.json, project/src/config.js, project/src/pages/Auth/Forgotpassword.js, project/yarn.lock
=> Api profile page

project/package-lock.json, project/src/navigation/BottomTabNavigator.js, project/src/pages/Profile/EditProfilePage.js, project/yarn.lock
=> Api create post

project/android/app/src/main/AndroidManifest.xml, project/package-lock.json, project/src/components/TweetCard.js, project/src/navigation/BottomTabNavigator.js, project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Profile/EditProfilePage.js, project/src/pages/Profile/Profilescreen.js, project/yarn.lock
=> Penambahan fitur create & read post

project/src/components/TweetCard.js, project/src/navigation/BottomTabNavigator.js, project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Profile/EditProfilePage.js, project/src/pages/Profile/Profilescreen.js, project/src/pages/Profile/Replyscreen.js, project/src/pages/Settings/Settingsscreen.js
+   Penambahan skeleton loading dan sesuaikan jarak di Profilescreen.js
- Tambahkan state `loading` untuk mengelola status loading.
- Tampilkan skeleton loading untuk banner dan profile picture saat data di-fetch.
- Tambahkan delay 1 detik sebelum mengubah `loading` ke false.
- Sesuaikan jarak di sekitar skeleton profile picture untuk mencegah tabrakan.
- Tambahkan `marginTop: 10` pada `skeletonProfile`.
- Tambahkan `marginLeft: 10` pada `skeletonText`.
- Perbarui fungsi `getData` untuk mengambil data pengguna dan mengatur state.
- Tambahkan `useEffect` untuk mengambil data secara berkala setiap 2 detik.
- Perbarui gaya untuk menyertakan penyesuaian jarak baru pada elemen skeleton.
+   Tambahkan tombol logout di Settingsscreen.js
- Tambahkan ikon logout menggunakan …
=> Update Frontend ++

project/App.js, project/package-lock.json, project/src/components/TweetCard.js, project/src/navigation/BottomTabNavigator.js, project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Profile/EditProfilePage.js, project/yarn.lock
=> push terakhir sebelum sprint 3

project/android/app/src/main/AndroidManifest.xml, project/android/gradle/wrapper/gradle-wrapper.properties, project/package-lock.json, project/package.json, project/src/navigation/BottomTabNavigator.js, project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Profile/Profilescreen.js, project/yarn.lock
create postnya belum bisa kombinasi file kek : video-image
=> Create Post Fixed

project/package-lock.json, project/src/components/BottomSheet.js, project/src/components/TweetCard.js, project/src/config.js, project/src/pages/Auth/Signinscreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Other/Marksscreen.js, project/src/pages/Profile/Likescreen.js, project/src/pages/Profile/Mediascreen.js, project/src/pages/Profile/Postscreen.js, project/src/pages/Profile/Profilescreen.js, project/src/pages/Profile/Userprofile.js, project/yarn.lock
perbarui dan perbaiki fitur See Another User Profile
=> Update see another user profile

Grand Theft Auto V.url, project/package-lock.json, project/src/components/BottomSheet.js, project/src/components/CommentCard.js, project/src/components/TweetCard.js, project/src/navigation/AuthNavigator.js, project/src/navigation/TopTabNavigator.js, project/src/pages/Home/CommentScreen.js, project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Profile/Profilescreen.js, project/src/pages/Profile/Userprofile.js
=> penambahan komen

project/src/components/CommentCard.js, project/src/components/TweetCard.js, project/src/pages/Home/CommentScreen.js, project/src/pages/Home/CreatePost.js
=> revisi komen ygy

package-lock.json, project/src/navigation/AuthNavigator.js, project/src/pages/Home/CommentScreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Home/ViewPost.js, project/src/pages/index.js
=> Localhostfe

project/src/components/BottomSheet.js, project/src/components/PinTweetCard.js, project/src/pages/Auth/CreatePassword.js, project/src/pages/Auth/Signinscreen.js, project/src/pages/Home/Homescreen.js, project/src/pages/Settings/UpdatePassword.js
=> Updated and Fixed Pin Post

project/src/components/PinTweetCard.js, project/src/components/TweetCard.js, project/src/navigation/UserTopTabNavigator.js, project/src/pages/Home/ViewPost.js, project/src/pages/Userprofile/Usermedia.js, project/src/pages/Userprofile/Userpost.js
=> Update dan Fix Bug

project/src/pages/Settings/AccountInformation.js
=> Added Number Phone

project/src/components/CommentCard.js, project/src/components/CommentSheet.js, project/src/components/PinTweetCard.js, project/src/components/TweetCard.js, project/src/pages/Home/ViewPost.js, project/src/pages/Settings/AccountInformation.js
=> Menambahkan NumberPhone dan

project/src/pages/Home/CreatePost.js, project/src/pages/Home/Homescreen.js, project/src/pages/Settings/VerifyAccount.js
=> various bug fixes

project/src/components/Admin/Statuscard.js, project/src/components/DeleteInfo.js
=> minor changes

project/src/components/PinTweetCard.js, project/src/components/TweetCard.js, project/src/navigation/BottomTabNavigator.js, project/src/navigation/DrawerNavigator.js, project/src/pages/Profile/Profilescreen.js
=> minor changes prot prot

project/src/components/Admin/ReportedUser.js, project/src/components/FollowCard.js, project/src/navigation/FollowTopTabNavigator.js, project/src/pages/Home/FollowerPage.js, project/src/pages/Home/FollowingPage.js, project/src/pages/Profile/Profilescreen.js, project/src/pages/Userprofile/Userprofile.js
=> Memperlengkap fitur follow

project/src/pages/Home/SearchPage.js, project/src/pages/Userprofile/Userprofile.js
=> Menambahkan fitur klik user dari search
